// EchoDotNetLiteLANBridge.dll (EchoDotNetLiteLANBridge)
//   Name: EchoDotNetLiteLANBridge
//   AssemblyVersion: 1.0.0.0
//   InformationalVersion: 1.0.0+cb7a08465ac80ce862063d85cf7c3cd6cfb81e91
//   TargetFramework: .NETStandard,Version=v2.1
//   Configuration: Release
//   Referenced assemblies:
//     EchoDotNetLite, Version=1.0.0.0, Culture=neutral
//     Microsoft.Extensions.Logging.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
//     netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
#nullable enable annotations

using System;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using EchoDotNetLite;
using EchoDotNetLiteLANBridge;

namespace EchoDotNetLiteLANBridge {
  public class LANClient :
    IDisposable,
    IPANAClient
  {
    public event EventHandler<(string, byte[])> OnEventReceived;

    public LANClient(ILogger<LANClient> logger) {}

    public void Dispose() {}
    public async Task RequestAsync(string address, byte[] request) {}
  }
}
// API list generated by Smdn.Reflection.ReverseGenerating.ListApi v1.3.0.0.
// Smdn.Reflection.ReverseGenerating.ListApi.Core v1.3.0.0 (https://github.com/smdn/Smdn.Reflection.ReverseGenerating)
