// Smdn.Net.EchonetLite.RouteB.Primitives.dll (Smdn.Net.EchonetLite.RouteB.Primitives-2.0.0)
//   Name: Smdn.Net.EchonetLite.RouteB.Primitives
//   AssemblyVersion: 2.0.0.0
//   InformationalVersion: 2.0.0+7829b96052cff6b82bd3e68fb0ced5454037c338
//   TargetFramework: .NETStandard,Version=v2.1
//   Configuration: Release
//   Referenced assemblies:
//     Microsoft.Extensions.DependencyInjection.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
//     Microsoft.Extensions.Logging.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
//     Smdn.Net.EchonetLite.Primitives, Version=2.0.0.0, Culture=neutral
//     netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
#nullable enable annotations

using System;
using System.Buffers;
using System.Net;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Smdn.Net.EchonetLite.RouteB.Credentials;
using Smdn.Net.EchonetLite.RouteB.Transport;
using Smdn.Net.EchonetLite.Transport;

namespace Smdn.Net.EchonetLite.RouteB.Credentials {
  public interface IRouteBCredential : IDisposable {
    void WriteIdTo(IBufferWriter<byte> buffer);
    void WritePasswordTo(IBufferWriter<byte> buffer);
  }

  public interface IRouteBCredentialIdentity {
  }

  public interface IRouteBCredentialProvider {
    IRouteBCredential GetCredential(IRouteBCredentialIdentity identity);
  }

  public static class RouteBCredentials {
    public const int AuthenticationIdLength = 32;
    public const int PasswordLength = 12;
  }
}

namespace Smdn.Net.EchonetLite.RouteB.Transport {
  public interface IRouteBEchonetLiteHandlerBuilder {
    IServiceCollection Services { get; }
  }

  public interface IRouteBEchonetLiteHandlerFactory {
    ValueTask<RouteBEchonetLiteHandler> CreateAsync(CancellationToken cancellationToken);
  }

  public abstract class RouteBEchonetLiteHandler : EchonetLiteHandler {
    protected RouteBEchonetLiteHandler(ILogger? logger, IServiceProvider? serviceProvider) {}

    public abstract IPAddress? PeerAddress { get; }

    public ValueTask ConnectAsync(IRouteBCredential credential, CancellationToken cancellationToken = default) {}
    protected abstract ValueTask ConnectAsyncCore(IRouteBCredential credential, CancellationToken cancellationToken);
    public ValueTask DisconnectAsync(CancellationToken cancellationToken = default) {}
    protected abstract ValueTask DisconnectAsyncCore(CancellationToken cancellationToken);
  }
}
// API list generated by Smdn.Reflection.ReverseGenerating.ListApi.MSBuild.Tasks v1.5.0.0.
// Smdn.Reflection.ReverseGenerating.ListApi.Core v1.3.1.0 (https://github.com/smdn/Smdn.Reflection.ReverseGenerating)
